### ISSUE TITLE
特殊ジャッジ対策

### ISSUE THREAD

**Issue by snuke** [kyuridenamida/ToolsForAtCoder#3]
誤差ジャッジや特殊ジャッジの時にsampleにACできないですが、sampleを通さなくてもsubmitできる機能があると嬉しいかも。（あと、sampleが0個の時はsubmitしないのは仕様ですか？）

**Comment by snuke** [comment]
コード見たら --f オプションというのがあった。

**Comment by kyuridenamida** [comment]
それは結構重要な課題です．誤差ジャッジに対応するべきだと思いました．
完全に特殊ジャッジみたいなのは諦めるしかないですが．
誤差ジャッジに関しては出現頻度が高いので，利便性のために，実数1つのやつくらいは対応できるようにしたい(オプションにするのが一番簡単かな，ただ出力の項の記述から誤差ジャッジか判断するくらいは余力があればしたい．
